// <auto-generated />
using System;
using IstropAviary.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IstropAviary.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802110335_AdvancedFeatures")]
    partial class AdvancedFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IstropAviary.API.Models.Aviary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Aviaries");
                });

            modelBuilder.Entity("IstropAviary.API.Models.Bird", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AviaryId")
                        .HasColumnType("integer");

                    b.Property<string>("BandNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BeakColor")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EyeColor")
                        .HasColumnType("text");

                    b.Property<int?>("FatherId")
                        .HasColumnType("integer");

                    b.Property<string>("FeatherCondition")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("HealthStatus")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int?>("MotherId")
                        .HasColumnType("integer");

                    b.Property<string>("Mutation")
                        .HasColumnType("text");

                    b.Property<int?>("NestId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RingColor")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AviaryId");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.HasIndex("NestId");

                    b.ToTable("Birds");
                });

            modelBuilder.Entity("IstropAviary.API.Models.CarePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("RelatedBirdId")
                        .HasColumnType("integer");

                    b.Property<int?>("RelatedNestId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RelatedBirdId");

                    b.HasIndex("RelatedNestId");

                    b.ToTable("CarePlans");
                });

            modelBuilder.Entity("IstropAviary.API.Models.Clutch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BandingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HatchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NestId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NestId");

                    b.ToTable("Clutches");
                });

            modelBuilder.Entity("IstropAviary.API.Models.Nest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AviaryId")
                        .HasColumnType("integer");

                    b.Property<string>("NestCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NextAction")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AviaryId");

                    b.ToTable("Nests");
                });

            modelBuilder.Entity("IstropAviary.API.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerCity")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PaymentType")
                        .HasColumnType("text");

                    b.Property<string>("SaleNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("IstropAviary.API.Models.SaleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BirdId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BirdId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleDetails");
                });

            modelBuilder.Entity("IstropAviary.API.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("IstropAviary.API.Models.Bird", b =>
                {
                    b.HasOne("IstropAviary.API.Models.Aviary", "Aviary")
                        .WithMany()
                        .HasForeignKey("AviaryId");

                    b.HasOne("IstropAviary.API.Models.Bird", "Father")
                        .WithMany()
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IstropAviary.API.Models.Bird", "Mother")
                        .WithMany()
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IstropAviary.API.Models.Nest", "Nest")
                        .WithMany()
                        .HasForeignKey("NestId");

                    b.Navigation("Aviary");

                    b.Navigation("Father");

                    b.Navigation("Mother");

                    b.Navigation("Nest");
                });

            modelBuilder.Entity("IstropAviary.API.Models.CarePlan", b =>
                {
                    b.HasOne("IstropAviary.API.Models.Bird", "RelatedBird")
                        .WithMany()
                        .HasForeignKey("RelatedBirdId");

                    b.HasOne("IstropAviary.API.Models.Nest", "RelatedNest")
                        .WithMany()
                        .HasForeignKey("RelatedNestId");

                    b.Navigation("RelatedBird");

                    b.Navigation("RelatedNest");
                });

            modelBuilder.Entity("IstropAviary.API.Models.Clutch", b =>
                {
                    b.HasOne("IstropAviary.API.Models.Nest", "Nest")
                        .WithMany()
                        .HasForeignKey("NestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nest");
                });

            modelBuilder.Entity("IstropAviary.API.Models.Nest", b =>
                {
                    b.HasOne("IstropAviary.API.Models.Aviary", "Aviary")
                        .WithMany()
                        .HasForeignKey("AviaryId");

                    b.Navigation("Aviary");
                });

            modelBuilder.Entity("IstropAviary.API.Models.SaleDetail", b =>
                {
                    b.HasOne("IstropAviary.API.Models.Bird", "Bird")
                        .WithMany()
                        .HasForeignKey("BirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IstropAviary.API.Models.Sale", "Sale")
                        .WithMany("SaleDetails")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bird");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("IstropAviary.API.Models.Sale", b =>
                {
                    b.Navigation("SaleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
